### ISSUE TITLE
site.url missing from generated index

### ISSUE THREAD

**Issue by jcayouette** [Mogztter/antora-site-generator-lunr#61]
In version 2.3.3 the index contains the correct site.url string. In the latest version its missing. Im not sure if this has to do with antora or the site generator. 

Works when you install using the **0.4.0** tag

Working in version 2.3.3
```
window.antoraLunr.init({"index":{"version":"2.3.3","fields":["title","name","text","component"],"fieldVectors":[["title/https://opensource.suse.com/doc-susemanager/suse-manager/common_gfdl1.2_i.html"
```

Broken in 2.3.8:
```
window.antoraLunr.init({"index":{"version":"2.3.8","fields":["title","name","text","component"],"fieldVectors":[["title//suse-manager/common_gfdl1.2_i.html"
```

**Comment by Mogztter** [comment]
We've removed the site.url from the index to make it portable. The latest version includes version 0.7.1 of Antora Lunr: https://github.com/Mogztter/antora-lunr/releases/tag/v0.7.0


> Don't forget to update your UI to at least define window.antora.basePath. This variable will be used to construct the complete URL of search results client-side:

```html
<script>
  window.antora = window.antora || {}
  window.antora.basePath = '{{or siteRootPath (or site.url siteRootUrl)}}'
</script>
```

In other words, you need to update your UI to configure `window.antora.basePath`. And don't forget to synchronize the https://github.com/Mogztter/antora-lunr/tree/v0.7.1/supplemental_ui directory.

Related issues: https://github.com/Mogztter/antora-lunr/issues/61

**Comment by Mogztter** [comment]
@jcayouette Can you please confirm that updating the UI fixed this issue? Can we close?

**Comment by Mogztter** [comment]
Closing, feel free to reopen if it still does not work.
