### ISSUE TITLE
Some times we get a TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by indigo423** [Mogztter/antora-site-generator-lunr#97]
We have included Antora with the antora-site-generator-lunr in our CI/CD pipeline. We see a flapping behavior always with the same error message in the same git repository like this here:

```
#!/bin/sh -eo pipefail
npm i -g antora-site-generator-lunr
DOCSEARCH_ENABLED=true DOCSEARCH_ENGINE=lunr NODE_PATH="$(npm -g root)" antora --generator antora-site-generator-lunr --stacktrace generate antora-playbook.yml

+ antora-site-generator-lunr@0.6.1
added 254 packages from 210 contributors in 11.703s
Error: Unknown TypeError: See cause (url: https://github.com/OpenNMS/opennms-js.git)
    at transformGitCloneError (/usr/local/lib/node_modules/antora-site-generator-lunr/node_modules/@antora/content-aggregator/lib/aggregate-content.js:794:22)
    at git.clone.then.then.catch (/usr/local/lib/node_modules/antora-site-generator-lunr/node_modules/@antora/content-aggregator/lib/aggregate-content.js:184:17)
Caused by: TypeError: Cannot read property 'length' of undefined
    at Inflate.push (/usr/local/lib/node_modules/antora-site-generator-lunr/node_modules/pako/lib/inflate.js:218:30)
    at listpack (/usr/local/lib/node_modules/antora-site-generator-lunr/node_modules/isomorphic-git/dist/for-node/isomorphic-git/index.js:3230:16)

Exited with code exit status 1

CircleCI received exit code 1
```

A manual re-run fixes the problem and it seems to us very hard to reproduce. Do you have any hints on how to debug or investigate this problem?

We use it in an open-source library and everything is in public. [Here](https://app.circleci.com/pipelines/github/OpenNMS/docs.opennms.com/500/workflows/9c94f76d-07af-4c99-a719-801090aa1e54/jobs/991) is the error message from the build fail. We running with Antora 2.3.4.

Thank you in advance

**Comment by Mogztter** [comment]
@indigo423 I think you should open an issue upstream https://gitlab.com/antora/antora. I don't think it's related to `antora-site-generator-lunr` because the error is thrown by `@antora/content-aggregator`:

```
at transformGitCloneError (/usr/local/lib/node_modules/antora-site-generator-lunr/node_modules/@antora/content-aggregator/lib/aggregate-content.js:794:22)
```

**Comment by indigo423** [comment]
> @indigo423 I think you should open an issue upstream https://gitlab.com/antora/antora. I don't think it's related to `antora-site-generator-lunr` because the error is thrown by `@antora/content-aggregator`:
> 
> ```
> at transformGitCloneError (/usr/local/lib/node_modules/antora-site-generator-lunr/node_modules/@antora/content-aggregator/lib/aggregate-content.js:794:22)
> ```

Thanks for the response, I'll open it upstream and I think we can close this here.

**Comment by mojavelinux** [comment]
I don't think there's anything Antora can do to solve this issue. It looks like there are instances when GitHub is returning an incomplete response, and hence the git client fails to parse it. That explains why trying it again succeeds. It's possible isomorphic-git could retry in the case this happens.

**Comment by indigo423** [comment]
> I don't think there's anything Antora can do to solve this issue. It looks like there are instances when GitHub is returning an incomplete response, and hence the git client fails to parse it. That explains why trying it again succeeds. It's possible isomorphic-git could retry in the case this happens.

@mojavelinux Just FYI: there is something going on in isomorphic-git https://github.com/isomorphic-git/isomorphic-git/pull/1400

**Comment by Mogztter** [comment]
As soon as Antora upgrades to `isomorphic-git` >= 1.9.2, this issue should be fixed.
I can see that the master branch is already using `~1.9`, not sure if the next 3.0.0 alpha release will contain this upgrade. The latest 3.0.0 alpha release (https://gitlab.com/antora/antora/-/blob/v3.0.0-alpha.7/packages/content-aggregator/package.json#L25) is using `~1.8`.

**Comment by mojavelinux** [comment]
Wow, we really lucked out here. The isomorphic-git upgrade that includes this fix will be available in the next Antora alpha.
